server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: Grupo06
      password: bc24_06
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictorCanchica/BC24_ConfigServer
          search-paths: /
          default-label: "dev"
